# Generated by Django 4.1.7 on 2023-03-09 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supercchic_api', '0002_alter_products_discount_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(default='test.wepb', upload_to='product_img/'),
            preserve_default=False,
        ),
    ]
