# Generated by Django 4.1.7 on 2023-03-09 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supercchic_api', '0003_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
