# Generated by Django 4.1.7 on 2023-03-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supercchic_api', '0004_alter_products_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='panierrow',
            name='quantity',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
